app/dashboard/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, TextAreaField, BooleanField
from wtforms.validators import DataRequired, ValidationError, Email, EqualTo
from wtforms.validators import Length
from app.models import User


class RegistrationForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired(), Length(min=2)])
    email = StringField("Email", validators=[DataRequired(), Email()])
    password = PasswordField("Password", validators=[DataRequired()])
    password2 = PasswordField(
        "Repeat Password", validators=[DataRequired(), EqualTo("password")]
    )
    administrator = BooleanField("Administrator")

    def validate_username(self, username):
        """
        Check if a user exists or not. If Exists, Raise ValidationError.
        """
        user = User.query.filter_by(username=username.data).first()

        if user is not None:
            raise ValidationError("Please use a different username.")

    def validate_email(self, email):
        """
        Check if an Email exists or not. If Exists, Raise ValidationError.
        """
        user = User.query.filter_by(email=email.data).first()

        if user is not None:
            raise ValidationError("Please use a different email address.")


class EditProfileForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired(), Length(min=2)])
    about_me = TextAreaField("About me", validators=[Length(min=0, max=500)])
    email = StringField("Email", validators=[DataRequired(), Email()])
    screen_name = StringField("Screen Name", validators=[DataRequired()])
    website = StringField("Website")
    github = StringField("GitHub")
    twitter = StringField("Twitter")

    def __init__(self, original_username, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.original_username = original_username

    def validate_username(self, username):
        """
        Check if a user exists or not. If Exists, Raise ValidationError.
        """

        if username.data != self.original_username:
            user = User.query.filter_by(username=self.username.data).first()

            if user is not None:
                raise ValidationError("Please use a different username.")


class PostForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired(), Length(min=2, max=280)])
    url = StringField("Title", validators=[DataRequired(), Length(min=5, max=280)])
    markdown_url = StringField(
        "Markdown URL", validators=[DataRequired(), Length(min=10)]
    )
    tags = StringField("Tags", validators=[DataRequired(), Length(min=2)])
    img_url = StringField("Image URL")
    summary = TextAreaField("Summary", validators=[DataRequired(), Length(min=50)])


class PinMsgForm(FlaskForm):
    home_msg = TextAreaField(
        "Home Message", validators=[DataRequired(), Length(min=1, max=4000)]
    )
    home_enable = BooleanField("Enable")

app/dashboard/__init__.py
from flask import Blueprint

bp = Blueprint('dashboard', __name__)

from app.dashboard import routes

app/dashboard/routes.py
from flask import render_template, flash, redirect, url_for, request
from flask_login import login_required, current_user
from app.dashboard import bp
from app.dashboard.forms import RegistrationForm, EditProfileForm, PostForm, PinMsgForm
from app.models import User, Post, Tag, PinedMsg
from app import db
import re
from datetime import datetime


@bp.before_request
def before_request():
    """ Save the las activity of the user. """
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()


@bp.route("/overview")
@login_required
def overview():
    """ Dashboard Overview. """
    # For avatar and user name in the dashboard
    user = User.query.filter_by(username=current_user.username).first()
    my_posts = Post.query.filter_by(user_id=current_user.id).order_by(
        Post.timestamp.desc()
    )

    # cant use my post to check if there are articles or not,
    # have to use this query:
    posts = Post.query.filter_by(user_id=current_user.id).first()

    return render_template(
        "dashboard/overview.html",
        title="Dashboard",
        my_posts=my_posts,
        overview_active="is-active",
        user=user,
        post_list=posts,
    )


@bp.route("/manage_articles")
@login_required
def manage_articles():
    """ Dashboard Article Manager: Edit, Delete and Create. """
    # All posts ordered by date
    posts_list = Post.query.first()
    posts = Post.query.filter_by().order_by(Post.timestamp.desc())

    return render_template(
        "dashboard/overview.html",
        title="Manage Articles",
        my_posts=posts,
        articles_active="is-active",
        post_list=posts_list,
    )


@bp.route("/add_user", methods=["GET", "POST"])
@login_required
def add_user():
    """ Dashboard New User. """
    form = RegistrationForm()

    if form.validate_on_submit():

        # if administrator check box is selected, create an administrator
        if form.administrator.data:
            user = User(
                username=form.username.data,
                email=form.email.data,
                is_administrator=True,
            )
        else:
            user = User(username=form.username.data, email=form.email.data)

        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash("Account created for {}.".format(form.username.data))

        return redirect(url_for("dashboard.manage_users"))

    return render_template(
        "dashboard/add_user.html", title="Add User", form=form, add_active="is-active"
    )


@bp.route("/manage_users")
@login_required
def manage_users():
    """ Dashboard User Manager: Edit, Delete and Create. """
    all_users = User.query.all()

    return render_template(
        "dashboard/manage_users.html",
        title="Manage Users",
        all_users=all_users,
        users_active="is-active",
    )


@bp.route("/edit_profile/<username>", methods=["GET", "POST"])
@login_required
def edit_profile(username):
    """ Dashboard Profile Manager: Edit, Delete and Create. """
    if current_user.username != username:
        flash("You can't edit other users profiles.")

        return redirect(url_for("dashboard.overview"))

    user = User.query.filter_by(username=username).first_or_404()
    form = EditProfileForm(user.username)

    if form.validate_on_submit():
        user.username = form.username.data
        user.about_me = form.about_me.data
        user.email = form.email.data
        user.screen_name = form.screen_name.data
        user.website = form.website.data
        user.github = form.github.data
        user.twitter = form.twitter.data
        db.session.commit()
        flash("{}, your changes have been saved.".format(form.username.data))
        return redirect(url_for("dashboard.overview"))

    elif request.method == "GET":
        form.username.data = user.username
        form.about_me.data = user.about_me
        form.email.data = user.email
        form.screen_name.data = user.screen_name
        form.website.data = user.website
        form.github.data = user.github
        form.twitter.data = user.twitter

    return render_template(
        "dashboard/edit_profile.html",
        form=form,
        user=user,
        title="Edit Profile",
        edit_active="is-active",
    )


@bp.route("/new_post", methods=["GET", "POST"])
@login_required
def new_post():
    """ Dashboard: Create a New Article. Same as Edit Article. """
    form = PostForm()

    if form.validate_on_submit():
        post = Post(
            markdown_url=form.markdown_url.data,
            author=current_user,
            title=form.title.data,
            url=form.url.data,
            img_url=form.img_url.data,
            summary=form.summary.data,
        )

        # split the tags by the comas
        post_tags = form.tags.data.replace(" ", "").split(",")

        # check if the tag exists to append it to the post. Else, create it
        Tag.add_or_create_tags(post_tags, post)

        # add tag and post
        db.session.add(post)

        # commit to the db
        db.session.commit()
        flash('"{}" is now live!'.format(form.title.data))

        return redirect(url_for("dashboard.overview"))

    return render_template(
        "dashboard/new_post.html", title="New Post", form=form, post_active="is-active"
    )


@bp.route("/edit_post/<url>", methods=["GET", "POST"])
@login_required
def edit_post(url):
    post = Post.query.filter_by(url=url).first_or_404()
    form = PostForm()

    if form.validate_on_submit():
        post.title = form.title.data
        post.url = form.url.data
        post.markdown_url = form.markdown_url.data
        post.summary = form.summary.data
        post.img_url = form.img_url.data

        # split the tags by comas
        post_tags = form.tags.data.replace(" ", "").split(",")

        # check for deleted tags
        Tag.check_deleted_tags(post, post_tags)

        # check for existing tags
        Tag.update_tags(post_tags, post)

        db.session.commit()
        flash('Changes on "{}" have been saved.'.format(form.title.data))

        return redirect(url_for("dashboard.overview"))

    elif request.method == "GET":
        form.title.data = post.title
        form.url.data = post.url
        form.markdown_url.data = post.markdown_url
        form.summary.data = post.summary
        form.img_url.data = post.img_url
        # use regex to format the tags
        tag_regex = re.compile(r"\[(.*)\]")
        mo = tag_regex.search(str(post.tag.all()))
        form.tags.data = mo.group(1)

    return render_template(
        "dashboard/new_post.html",
        post=post,
        form=form,
        title="Edit Post",
        overview_active="is-active",
    )


@bp.route("/site_configuration", methods=["GET", "POST"])
@login_required
def site_configuration():
    """ For now, just edit the Pinned Notification on the Index. """

    form = PinMsgForm()
    msg = PinedMsg.query.filter_by(id=1).first()

    if form.validate_on_submit():
        if msg:
            msg.home_msg = form.home_msg.data
            msg.home_enable = form.home_enable.data
        else:
            msg = PinedMsg(
                home_msg=form.home_msg.data, home_enable=form.home_enable.data
            )
            db.session.add(msg)

        db.session.commit()
        flash("The Pinned message has ben Updated.")

        return redirect(url_for("dashboard.site_configuration"))

    # check if there is a msg created and get it
    elif request.method == "GET":
        if msg:
            form.home_msg.data = msg.home_msg

            if msg.home_enable:
                enabled = True
            else:
                enabled = False
        else:
            enabled = "None"

    return render_template(
        "dashboard/site_configuration.html",
        title="Site Configuration",
        form=form,
        config_active="is-active",
        enabled=enabled,
    )


@bp.route("/delete_user/<id>", methods=["POST"])
@login_required
def delete_user(id):
    user = User.query.filter_by(id=id).first_or_404()
    db.session.delete(user)
    db.session.commit()
    flash("User {} has been Deleted".format(user.username))

    return redirect(url_for("dashboard.manage_users"))


@bp.route("/delete_post/<url>", methods=["GET", "POST"])
@login_required
def delete_post(url):
    post = Post.query.filter_by(url=url).first_or_404()
    db.session.delete(post)
    db.session.commit()
    flash('"{}" has been Deleted'.format(post.title))

    return redirect(url_for("dashboard.overview"))

app/templates/dashboard/_dash_menu.html
<!-- menú -->
<aside class="menu hero">
  <p class="menu-label">
    Blog
  </p>
  <ul class="menu-list">
    <li>
      <a href="{{ url_for('dashboard.overview') }}" class="{{ overview_active }}">
        <span class="icon">
          <i class="fas fa-tachometer-alt"></i>
        </span>
        Overview</a>
    </li>
    <li>
      <a href="{{ url_for('dashboard.new_post') }}" class="{{ post_active }}">
        <span class="icon">
          <i class="fas fa-plus"></i>
        </span>
        New Article</a>
    </li>
    <li>
      <a href="{{ url_for( 'dashboard.edit_profile', username=current_user.username) }}" class="{{ edit_active }}">
        <span class="icon">
          <i class="fas fa-user"></i>
        </span>
        Edit Profile </a>
    </li>
  </ul>
  {% if current_user.is_administrator %}
  <p class="menu-label">
    Administration
  </p>
  <ul class="menu-list">
    <li>
      <a href="{{ url_for('dashboard.site_configuration') }}" class="{{ config_active }}">
        <span class="icon">
          <i class="fas fa-cogs"></i>
        </span>
        Site Configuration</a>
    </li>
    <li>
      <a href="{{ url_for('dashboard.manage_articles') }}" class="{{ articles_active }} ">
        <span class="icon">
          <i class="fas fa-file-alt"></i>
        </span>
        Manage Articles</a>
    </li>
    <li>
      <a href="#" class="{{ tags_active }}">
        <span class="icon">
          <i class="fas fa-tags"></i>
        </span>
        Manage Tags</a>
    </li>
    <li>
      <a href="{{ url_for('dashboard.manage_users') }}" class="{{ users_active }}">
        <span class="icon">
          <i class="fas fa-users"></i>
        </span>
        Manage Users</a>
    </li>
    <li>
      <a href="{{ url_for( 'dashboard.add_user') }}" class="{{ add_active }} ">
        <span class="icon">
          <i class="fas fa-user-plus"></i>
        </span>
        Add User</a>
    </li>
  </ul>
  {% endif %}
</aside>

app/templates/dashboard/add_user.html
{% extends "base.html" %}

{% block content %}
<section class="section container">
  <div class="columns is-mobile">

    <!-- dashboard menu -->
    <div class="column is-one-quarter">
      {% include 'dashboard/_dash_menu.html' %}
    </div>

    <!-- dashboard content -->
    <div class="column is-5 section">
      <div class=" ">
        <!-- form -->
        <form action="" method="POST" autocomplete="off">
          {{ form.hidden_tag() }}

          <!-- username -->
          <div class="field">
            <p class="control">{{ form.username(class="text-field-addUser", placeholder="User Name", autocomplete="off") }}</p>
            {% for error in form.username.errors %}
              <span class="help" style="color: red;">{{ error }}</span>
            {% endfor %}
          </div>

          <!-- email -->
          <div class="field">
            <p class="control">{{ form.email(class="text-field-addUser", type="email", placeholder="User Email", autocomplete="off") }}</p>
            {% for error in form.email.errors %}
              <span class="help" style="color: red;">{{ error }}</span>
            {% endfor %}
          </div>

          <!-- password -->
          <div class="field">
            <p class="control">{{ form.password(class="text-field-addUser", placeholder="Password", autocomplete="off") }}</p>
            {% for error in form.password.errors %}
              <span class="help" style="color: red;">{{ error }}</span>
            {% endfor %}
          </div>

          <!-- password 2 -->
          <div class="field">
            <p class="control">{{ form.password2(class="text-field-addUser", placeholder="Repeat Password", autocomplete="off") }}</p>
            {% for error in form.password2.errors %}
              <span class="help" style="color: red;">{{ error }}</span>
            {% endfor %}
          </div>

          <div class="field">
            <p>{{ form.administrator(class="checkbox check-space form-checkbox", type="checkbox") }} {{ form.administrator.label
              }}
            </p>
          </div>

          <!-- register button -->
          <div class="field">
            <p class="control">
              <button class="submit-button addUser-form">
                Add User
              </button>
            </p>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

app/templates/dashboard/edit_profile.html
{% extends "base.html" %}

{% block content %}
<section class="section container">
  <div class="columns">

    <!-- dashboard menu -->
    <div class="column is-one-quarter">
      {% include 'dashboard/_dash_menu.html' %}
    </div>

    <!-- dashboard content -->
    <div class="column">
      <form action="" method="POST">
        {{ form.hidden_tag() }}

        <!-- username -->
        <div class="field">
          <label class="label">{{ form.username.label }}</label>
          <p class="control">{{ form.username(class="input", type="text") }}</p>
          {% for error in form.username.errors %}
            <span class="help" style="color: red;">{{ error }}</span>
          {% endfor %}<br>
        </div>

        <!-- screen name -->
        <div class="field">
          <label class="label">{{ form.screen_name.label }}</label>
          <p class="control">{{ form.screen_name(class="input", type="text") }}</p>
          {% for error in form.screen_name.errors %}
            <span class="help" style="color: red;">{{ error }}</span>
          {% endfor %}<br>
        </div>

        <!-- email -->
        <div class="field">
          <label class="label">{{ form.email.label }}</label>
          <p class="control">{{ form.email(class="input", type="email") }}</p>
          {% for error in form.email.errors %}
            <span class="help" style="color: red;">{{ error }}</span>
          {% endfor %}<br>
        </div>

        <!-- social media -->
        <div class="field is-horizontal">
          <div class="field-body">

            <!-- twitter -->
            <div class="field">
              <label class="label">{{ form.twitter.label }}</label>
              <p class="control">{{ form.twitter(class="input", type="url") }}</p>
              {% for error in form.twitter.errors %}
                <span class="help" style="color: red;">{{ error }}</span>
              {% endfor %}
            </div>

            <!-- github -->
            <div class="field">
              <label class="label">{{ form.github.label }}</label>
              <p class="control">{{ form.github(class="input", type="url") }}</p>
              {% for error in form.github.errors %}
                <span class="help" style="color: red;">{{ error }}</span>
              {% endfor %}
            </div>

            <!-- website -->
            <div class="field">
              <label class="label">{{ form.website.label }}</label>
              <p class="control">{{ form.website(class="input", type="url") }}</p>
              {% for error in form.website.errors %}
                <span class="help" style="color: red;">{{ error }}</span>
              {% endfor %}
            </div>
          </div><br>
        </div>

        <!-- about -->
        <div class="field">
          <label class="label">{{ form.about_me.label }}</label>
          <div class="control">
            {{ form.about_me(class="textarea", type="textarea", rows=5, placeholder="Markdown Enabled") }}
          </div><br>
        </div>

        <!-- send -->
        <div class="field">
          <p class="control">
            <button class="button is-active">
              Submit
            </button>
          </p>
        </div>
      </form>
    </div>
  </div>
</section>
{% endblock content %}

app/templates/dashboard/manage_users.html
{% extends "base.html" %}

{% block content %}
<section class="section container">
  <div class="columns">

    <!-- dashboard menu -->
    <div class="column is-one-quarter">
      {% include 'dashboard/_dash_menu.html' %}
    </div>

    <!-- dashboard content -->
    <div class="column">

      <!-- table of users -->
      <div class="columns is-centered">
        <table class="table is-striped is-hoverable table is-fullwidth">

          <!-- titles -->
          <thead>
            <tr>
              <th>
                <abbr title="Date">Id</abbr>
              </th>
              <th>
                <abbr title="Date">Last Seen</abbr>
              </th>
              <th>
                <abbr title="Author">Username</abbr>
              </th>
              <th>
                <abbr title="Author">Screen Name</abbr>
              </th>
              <th>
                <abbr title="Posts">Articles</abbr>
              </th>
              <th>
                <abbr title="Edit"></abbr>
              </th>
              <th>
                <abbr title="Delete"></abbr>
              </th>
          </thead>

          <!-- users -->
          <tbody>
            {% for user in all_users %}
              <tr>
                <td>{{ user.id }}</td>
                <td>{{ moment(user.last_seen).format('L') }}</td>
                <td>{{ user.username }}</td>
                <td>
                  <a href="{{ url_for('main.author', username=user.username) }}">{{ user.screen_name }}</a>
                </td>
                <td class="has-text-right">{{user.post.count()}}</td>
                <td>
                  <a href="{{ url_for('dashboard.edit_profile', username=user.username) }}" class="button is-link">Edit</a>
                </td>
                <td>
                  <form action="{{ url_for('dashboard.delete_user', id=user.id) }}" method=post>
                    <input type="hidden" name="entry_id" value="{{ loop.revindex }}">
                    <button class="button is-danger">Delete</button>
                  </form>
                </td>
              </tr>
            {% endfor %}
          </tbody>

        </table>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

app/templates/dashboard/new_post.html
{% extends "base.html" %}
<!--  -->
{% block content %}
<section class="section container">
  <div class="columns">

    <!-- dashboard menu -->
    <div class="column is-one-quarter">
      {% include 'dashboard/_dash_menu.html' %}
    </div>

    <!-- dashboard content -->
    <div class="column">
      <form method="post">
        {{ form.hidden_tag() }}

        <!-- title -->
        <div class="field">
          <label class="label">Title</label>
          <p class="control">{{ form.title(class="input", type="text", placeholder="Title") }}</p>
          {% for error in form.title.errors %}
            <span class="help" style="color: red;">{{ error }}</span>
          {% endfor %} <br>
        </div>

        <!-- Summary -->
        <div class="field">
            <label class="label">Summary</label>
          <p class="control">{{ form.summary(class="textarea", rows=3, type="textarea", placeholder="Article Summary") }}</p>
          {% for error in form.summary.errors %}
            <span class="help" style="color: red;">{{ error }}</span>
          {% endfor %} <br>
        </div>

        <!-- image url -->
        <div class="field">
          <label class="label">Image URL</label>
          <p class="control">{{ form.img_url(class="input", type="url", placeholder="Image URL") }}</p>
          {% for error in form.img_url.errors %}
            <span class="help" style="color: red;">{{ error }}</span>
          {% endfor %} <br>
        </div>

        <!-- body markdown url -->
        <div class="field">
          <label class="label">Body Markdown URL</label>
          <div class="control">
            {{ form.markdown_url(class="input", type="url", placeholder="Markdown URL Article") }}
          </div>
          {% for error in form.markdown_url.errors %}
            <span class="help" style="color: red;">{{ error }}</span>
          {% endfor %} <br>
        </div>

        <!-- tags -->
        <div class="field">
          <label class="label">Tags</label>
          <p class="control">{{ form.tags(class="input",placeholder="Tags: Ex.: python, flask, django", type="text") }}</p>
          {% for error in form.tags.errors %}
            <span class="help" style="color: red;">{{ error }}</span>
          {% endfor %} <br>
        </div>

        <!-- url -->
        <div class="field">
          <label class="label">Article URL</label>
          <p class="control">{{ form.url(class="input", type="text", placeholder="Article URL") }}</p>
          {% for error in form.url.errors %}
            <span class="help" style="color: red;">{{ error }}</span>
          {% endfor %} <br>
        </div>

        <!-- submit button -->
        <div class="field">
          <p class="control">
            <button class="button">
              Submit
            </button>
          </p>
        </div>
      </form>
    </div>
  </div>
</section>
{% endblock content %}

app/templates/dashboard/overview.html
{% extends "base.html" %}

{% block content %}
<section class="section container">
  <div class="columns">

    <!-- dashboard menu -->
    <div class="column is-one-quarter">
      {% include 'dashboard/_dash_menu.html' %}
    </div>

    <!-- dashboard content -->
    <div class="column">
      <!-- post list -->
      <div class="columns is-centered">

        {% if post_list %}
          <table class="table is-striped is-hoverable table is-fullwidth">

            <!-- titles -->
            <thead>
              <tr>
                <th>
                  <abbr title="Date">Id</abbr>
                </th>
                <th>
                  <abbr title="Date">Date</abbr>
                </th>
                <th>
                  <abbr title="Author">Author</abbr>
                </th>
                <th>
                  <abbr title="Title">Article</abbr>
                </th>
                <th>
                  <abbr title="Edit"></abbr>
                </th>
                <th>
                  <abbr title="Delete"></abbr>
                </th>
            </thead>

            <!-- posts -->
            <tbody>
              {% for post in my_posts %}
                <tr>
                  <td>{{ post.id }}</td>
                  <td>{{ moment(post.timestamp).format('L') }}
                  </td>
                  <td>
                    <a href="{{ url_for('main.author', username=post.author.username) }}">{{ post.author.screen_name }}</a>
                  </td>
                  <td>
                    <a href="{{ url_for('main.article', url=post.url) }}">{{ post.title }}</a>
                  </td>
                  <td>
                    <a href="{{ url_for('dashboard.edit_post', url=post.url) }}" class="button is-link">Edit</a>
                  </td>
                  <td>
                    <form action="{{ url_for('dashboard.delete_post', url=post.url) }}" method=post>
                      <input type="hidden" name="entry_id" value="{{ loop.revindex }}">
                      <button class="button is-danger">Delete</button>
                    </form>
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        {% else %}
          <h1 class="title is-1 has-text-centered no-articles-dash">Nothing Yet 🙄</h1>
        {% endif %}
      </div>
    </div>
  </div>
</section>
{% endblock content %}

app/templates/dashboard/site_configuration.html
{% extends "base.html" %}

{% block content %}
<section class="section container">
  <div class="columns">

    <!-- dashboard menu -->
    <div class="column is-one-quarter">
      {% include 'dashboard/_dash_menu.html' %}
    </div>

    <!-- site configuration content -->
    <div class="column">

      <!-- home pinned post -->
      <h1 class="subtitle is-3 config-title">Pinned Messages</h1>

      <!-- form pinned post -->
      <form method="post">
        <div class="level">
          <label class="label">Python Cheatsheet Message</label>
          <!-- enable switch -->
          <label class="switch level-right">
            {% if enabled %}
              {{ form.home_enable(class="checkbox", checked=True) }}
            {% else %}
              {{ form.home_enable(class="checkbox") }}
            {% endif %}
            <span class="slider round"></span>
          </label>
        </div>

        {{ form.hidden_tag() }}
        {{ form.home_msg(class="textarea", type="textarea", rows=9, placeholder="Markdown Enabled") }}
        <br>

        <!-- update button -->
        <div class="field level-left">
          <p class="control">
            <button class="button">
              Update
            </button>
          </p>
        </div>
      </form>

    </div>
  </div>
</section>
{% endblock content %}