app/main/forms.py
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired
from wtforms import StringField
from flask import request


class SearchForm(FlaskForm):
    q = StringField("Search", validators=[DataRequired()])

    def __init__(self, *args, **kwargs):

        if "formdata" not in kwargs:
            kwargs["formdata"] = request.args

        if "csrf_enabled" not in kwargs:
            kwargs["csrf_enabled"] = False

        super(SearchForm, self).__init__(*args, **kwargs)

app/main/__init__.py
from flask import Blueprint

bp = Blueprint("main", __name__)

from app.main import routes

app/main/routes.py
from flask import (
    render_template,
    url_for,
    request,
    current_app,
    redirect,
    send_from_directory,
    g,
)
from app.main import bp
from app.models import User, Post, Tag, PinedMsg
import requests
import mistune
from app.main.forms import SearchForm


@bp.before_app_request
def before_request():
    g.search_form = SearchForm()
    g.search_switch = current_app.config["SEARCH_SWITCH"]
    g.site_name = current_app.config["SITE_NAME"]
    g.md = mistune.Markdown()  # parse md to html
    g.all_tags = Tag.query.all()


@bp.route("/index")
@bp.route("/")
def index():
    # get the cheatsheet form the repository
    pysheet = requests.get(current_app.config["PYSHEET_URL"]).text

    # get the pinned msg and check if its enabled
    pinned_msg = PinedMsg.query.filter_by(id=1).first()

    return render_template(
        "main/index.html",
        pysheet=pysheet,
        title="Python Cheatsheet",
        pinned_msg=pinned_msg,
    )


@bp.route("/blog")
def blog():
    # all posts
    posts = Post.query.all()

    # pagination
    page = request.args.get("page", 1, type=int)
    all_posts = Post.query.order_by(Post.timestamp.desc()).paginate(
        page, current_app.config["POSTS_PER_PAGE"]
    )

    # get the next page url
    next_url = (
        url_for("main.blog", page=all_posts.next_num) if all_posts.has_next else None
    )

    # get the previous page url
    prev_url = (
        url_for("main.blog", page=all_posts.prev_num) if all_posts.has_prev else None
    )

    return render_template(
        "main/blog.html",
        title="Blog",
        all_posts=all_posts,
        next_url=next_url,
        prev_url=prev_url,
        blog_posts=posts,
    )


@bp.route("/blog/tag/<tag>")
def tag(tag):
    tag = Tag.query.filter_by(name=tag).first()
    posts = tag.posts.order_by(Post.timestamp.desc())
    title = "Tag: {}".format(tag.name)

    return render_template("main/tag_articles.html", title=title, tag=tag, posts=posts)


@bp.route("/blog/<url>")
def article(url):
    post = Post.query.filter_by(url=url).first_or_404()
    body = requests.get(post.markdown_url).text
    is_article = True

    return render_template(
        "main/article.html",
        post=post,
        title=post.title,
        md_body=body,
        is_article=is_article,
    )


@bp.route("/contribute")
def contribute():
    contribute_r = requests.get(current_app.config["CONTRIBUTING"])
    contribute = contribute_r.text

    return render_template(
        "main/md_pages.html", title="Contribute", md_render=contribute
    )


@bp.route("/about")
def about():
    about_r = requests.get(current_app.config["ABOUT"])
    about = about_r.text

    return render_template("main/md_pages.html", title="About", md_render=about)


@bp.route("/author/<username>")
def author(username):
    user = User.query.filter_by(username=username).first_or_404()
    if user.about_me:
        about_me = user.about_me
    else:
        about_me = ""

    if user.screen_name:
        author = "About {}".format(user.screen_name)
    else:
        author = "About {}".format(user.username)

    my_posts = Post.query.filter_by(user_id=user.id).order_by(Post.timestamp.desc())

    return render_template(
        "main/author.html",
        user=user,
        my_posts=my_posts,
        title=author,
        about_me=about_me,
    )


@bp.route("/search")
def search():
    if not g.search_form.validate():
        return redirect(url_for("main.blog"))

    page = request.args.get("page", 1, type=int)
    posts, total = Post.search(
        g.search_form.q.data, page, current_app.config["POSTS_PER_PAGE"]
    )

    return render_template("main/search.html", title="Search", posts=posts, total=total)


@bp.route("/tags")
def tags():
    all_tags = Tag.query.all()
    return render_template("main/tags.html", title="Tags", all_tags=all_tags)


@bp.route("/sitemap.xml")
def sitemap():
    return send_from_directory("static", filename="sitemap.xml")


@bp.route("/robots.txt")
def robot():
    return send_from_directory("static", filename="robots.txt")


@bp.route("/BingSiteAuth.xml")
def bing():
    return send_from_directory("static", filename="BingSiteAuth.xml")


@bp.route("/.well-known/acme-challenge/4c8az6cAzIfCObgaIaxLLohgDeP-hYmiORG2wl-eAAw")
def acme1():
    return send_from_directory(
        "static/.well-known/acme-challenge",
        filename="4c8az6cAzIfCObgaIaxLLohgDeP-hYmiORG2wl-eAAw",
    )


@bp.route("/.well-known/acme-challenge/kwEzZO1xeSkpR9NntEbPT-5_adEQ72gKTcsq-5rIvPY")
def acme2():
    return send_from_directory(
        "static/.well-known/acme-challenge",
        filename="kwEzZO1xeSkpR9NntEbPT-5_adEQ72gKTcsq-5rIvPY",
    )

app/templates/main/_bottom_notification.html
<div id="bottomModal" class="end-modal has-text-centered is-centered">
  <button id="closeBottomModal" class="delete del is-pulled-right"></button>
  <div class="level">
    <div class="level-item">
      <figure class="image is-48x48">
            <a href="https://twitter.com/pyCheatsheet" target="_blank">
              <img src="{{ url_for( "static", filename="img/twitter.png" ) }}">
            </a>
      </figure>
      <p>Follow us on
        <a href="https://twitter.com/pyCheatsheet" target="_blank">Twitter</a>
        for a daily dose of Python, News and Articles 🖤
        <span class="hide-ctr-z"><br>Use <strong>ctrl+z</strong> to open the <i>quick search</i>.</span>
      </p>
    </div>
  </div>
</div>

app/templates/main/_default_sidebar.html
<!-- ads -->
<div>
  <br>
  <div id="codefund">
    <!-- fallback content -->
  </div>
</div><br>

<!-- subscribe -->
<div class="box has-text-centered subs is-hidden-mobile">
  <h3 class="has-text-weight-bold no-newsletter">Newsletters</h3><br>
  <p class="control has-icons-left has-icons-right no-unsubscribe">
    <input class="input" type="email" placeholder="Email" disabled>
    <span class="icon is-small is-left">
      <i class="fas fa-envelope"></i>
    </span>
  </p><br>
  <a class="button is-fullwidth" disabled>Subscribe</a>
  <p class="help has-text-left no-unsubscribe">Unsubscribe any time.</p>
</div><br>

{% if md_body %}
<!-- table of content -->
<div class="sticky-index is-hidden-mobile">
  <div id="index" class="box">
    <h3 class="no-newsletter">Table of Content</h3>
    <ul id="indexList"></ul>
  </div><br>

  <!-- tags in articles -->
  {% if g.all_tags %}
  <div>
    <p class="no-unsubscribe">
      <span class="icon">
        <i class="fas fa-tags"></i>
      </span>
      <span aria-hidden="true"></span>
      _Tags:
    </p>
    {% for tag in g.all_tags%}
    <a href="{{ url_for('main.tag', tag=tag.name) }}">
      <span class="tag is-warning tag-page">{{ tag.name }}</span>
    </a>
    {% endfor %}
  </div>
  {% endif %}
</div>
{% else %}
<!-- tags -->
{% if g.all_tags %}
<div class="is-hidden-mobile">
  <p class="no-unsubscribe">
    <span class="icon">
      <i class="fas fa-tags"></i>
    </span>
    <span aria-hidden="true"></span>
    _Tags:
  </p>
  {% for tag in g.all_tags%}
  <a href="{{ url_for('main.tag', tag=tag.name) }}">
    <span class="tag is-warning tag-page">{{ tag.name }}</span>
  </a>
  {% endfor %}
</div>
{% endif %}
{% endif %}

{% block js %}
{% if md_body %}
<script src={{ url_for( "static", filename="scripts/article-index.js" ) }} charset="utf-8 "></script>
{% endif %}
<!-- codefund -->
<script src="https://codefund.app/properties/92/funder.js" async="async"></script>
{% endblock js %}

app/templates/main/_mobile_article.html
  <!-- post on mobile -->
  <div class="is-hidden-tablet">

    <!-- article title -->
    <div class="header-content art-title">
      <div class="has-text-centered">
        <h2 class="title is-2 no-h1 is-size-4-mobile">
          {{ title }}
        </h2>
      </div>
    </div>

    <!-- post body -->
    <div class="content img-cent article-body">
      <br class="is-hidden-mobile">
      <p>{{ g.md(md_body)|safe }}</p>
      <hr>
      <div class="level">

      <!-- share -->
      <div class="level-right">
        <!-- buy me a coffee -->
        <div class="level-right">
          <link href="https://fonts.googleapis.com/css?family=Cookie" rel="stylesheet">
          <a class="bmc-button has-text-centered"
            target="_blank" href="https://www.buymeacoffee.com/8owKkSBUC"><img src="https://www.buymeacoffee.com/assets/img/BMC-btn-logo.svg"
            alt="Buy me a coffee"><span style="margin-left:5px">Buy me a coffee</span>
          </a>
        </div>
    </div>
  </div>

app/templates/main/_pagination.html
<!-- pagination -->
{% if blog_posts|length >= 6 %}
  <div class="container column is-7">
    <nav class="pagination is-centered" role="navigation" aria-label="pagination">

      <!-- prev page -->
      {% if prev_url %}
        <a href="{{ prev_url }}" class="pagination-previous">Previous</a>
      {% else %}
        <a href="#" class="pagination-previous" disabled>Previous</a>
      {% endif %}

      <!-- next page -->
      {% if next_url %}
        <a href="{{ next_url }}" class="pagination-next">Next page</a>
      {% else %}
        <a href="#" class="pagination-next" disabled>Next page</a>
      {% endif %}

      <!-- numbers -->
      <ul class="pagination-list">
        {% for page_num in all_posts.iter_pages() %}
          {% if page_num %}
            <!-- color num -->
            <li>
              {% if all_posts.page == page_num %}
                <a <a href="{{ url_for('main.blog', page=page_num) }}" class="pagination-link is-current">{{ page_num }}</a>
              {% else %}
                <a <a href="{{ url_for('main.blog', page=page_num) }}" class="pagination-link">{{ page_num }}</a>
              {% endif %}
            </li>
          {% else %}
            <li>
              <span class="pagination-ellipsis">&hellip;</span>
            </li>
          {% endif %}
        {% endfor %}
      </ul>
    </nav>
  </div>
{% endif %}

app/templates/main/_post.html
<section>
    <div class="is-multiline is-mobile is-centered">
      <div class="is-centered img-cent max-mobile">

        <!-- post title -->
        <div class="header-content">
          <div class="has-text-centered">
            <h2 class="title is-2 no-h1 is-size-4-mobile blog-title">
              <a href="{{ url_for('main.article', url=post.url) }}">{{ post.title }}</a>
            </h2>
          </div>
        </div>

        <!-- time and author name -->
        <div class="has-text-centered is-hidden-mobile article-botton-space">
          <p>By
            <a href="{{ url_for('main.author', username=post.author.username) }}">{{ post.author.screen_name }}</a>
            • {{ moment(post.timestamp).format('L') }} •
            <a href="{{ url_for('main.article', url=post.url) }}#comments">comments</a>
          </p>
        </div>

        <!-- article img -->
        <div>
          <img src="{{ post.img_url }}" alt="{{ post.title }}">
        </div>

        <!-- article summary -->
        <div class="content">
          <p>{{ g.md(post.summary)|safe }}</p>

          <!-- continue reading link for mobile -->
          <a class="is-pulled-right is-hidden-tablet" href="{{ url_for('main.article', url=post.url) }}"> Continue Reading...</a>

          <hr class="is-hidden-mobile">
          <div class="level is-hidden-mobile">
            <a class="button" href="{{ url_for('main.article', url=post.url) }}">
              Continue Reading
            </a>

            <!-- tags -->
            <div class="level">
              <p>Tags: {% for tag in post.tag %}
                <a href="{{ url_for('main.tag', tag=tag.name) }}">
                  <span class="tag is-warning">
                    {{tag.name}}
                  </span>
                </a>
                {% endfor %}
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <br>
  <br>
  <br>
</section>

app/templates/main/about.html
{% extends "base.html" %}
<!--  -->
{% block content %}
<link rel="stylesheet" href={{ url_for( "static", filename="css/cheatsheet.css" ) }}>
<section class="section container column is-8">
    <div>
        {{ about_md|safe }}
    </div>
</section>
{% endblock content %}

app/templates/main/article.html
{% extends "base_sidebar.html" %}

{% block seo %}
  <link rel="canonical" href="https://www.pythoncheatsheet.org/blog/{{ post.url }}">
  <meta property="og:url" content="https://www.pythoncheatsheet.org/blog/{{ post.url }}">
  <meta name="description" content="{{ g.md(post.summary)|striptags|truncate(250) }}">
  <meta property="og:description" content="{{ g.md(post.summary)|striptags }}">
  <meta name="twitter:description" content="{{ g.md(post.summary)|striptags }}" />
{% endblock seo %}

{% block schema %}
  <script type="application/ld+json">
  {
    "@context": "http://schema.org",
    "@type": "Article",
    "headline": "{{ post.title }}",

    "image": {
      "@type": "ImageObject",
      "url": "{{ post.img_url }}"
    },

    "mainEntityOfPage": {
      "@type": "WebPage",
      "@id": "https://www.pythoncheatsheet.org/blog/{{ post.url }}"
    },
    "datePublished": "{{ post.timestamp }}",
     "publisher": {
      "@type": "Organization",
      "name": "Python Cheatsheet",
      "logo": {
        "@type": "ImageObject",
        "url": "https://www.pythoncheatsheet.org{{ url_for( "static", filename="img/snake.png" ) }}",
        "width": 60,
        "height": 60
      }
    },
    "author": {
      "@type": "Organization",
      "name": "Python Cheatsheet",
      "url": "https://www.pythoncheatsheet.org",
      "logo": "https://www.pythoncheatsheet.org{{ url_for( "static", filename="img/snake.png" ) }}"
    },
    "description": "{{ g.md(post.summary)|striptags|truncate(250) }}"
  }
  </script>
{% endblock schema %}

{% block stylesheet %}
  <link rel="stylesheet" href={{ url_for( "static", filename="css/carbon-blog.min.css" ) }}>
{% endblock stylesheet %}


{% block main_column %}
  <!-- delete, edit, new -->
  {% if post.author.username == current_user.username %}
  <div id="articleEdits" class="column is-4 is-offset-8 del-edit-new-hidden editor ">
    <div class="level">

      <!-- delete -->
      <span class="icon level-item">
        <a id="deleteArticleBtn" class="articleDeleteModalBtn" href="javascript:void(0);">
          <i class="far fa-trash-alt"></i> Delete</a>
      </span>

      <!-- edit -->
      <span class="icon level-item">
        <a href="{{ url_for('dashboard.edit_post', url=post.url) }}">
          <i class="far fa-edit"></i> Edit</a>
      </span>

      <!-- new -->
      <span class="icon level-item">
        <a href="{{ url_for('dashboard.new_post') }}">
          <i class="fas fa-plus"></i> New</a>
      </span>
       </div>
    </div>
  {% endif %}

  <!-- article title -->
  <div class="header-content art-title">
    <div class="has-text-centered">
      <h1 class="title is-2 no-h1 is-size-4-mobile">
        {{ title }}
      </h1>
    </div>
  </div>

  <!-- time and author name -->
  <div class="has-text-centered article-botton-space">
    <p class="no-p">posted on
      <a>{{ moment(post.timestamp).format('L') }}</a> by
      <a href="{{ url_for('main.author', username=post.author.username) }}">{{ post.author.screen_name }}</a>
    </p>
  </div>

  <!-- post body -->
  <div class="content img-cent article-body">
    <!-- article img -->
    <div>
      <img src="{{ post.img_url }}" alt="{{ post.title }}">
    </div>
    <br>
    <p>{{ g.md(md_body)|safe }}</p>
    <hr>
    <div class="level">
      <!-- tags -->
      <div class="level-left">
        <p>Tags: {% for tag in post.tag %}
          <a href="{{ url_for('main.tag', tag=tag.name) }}">
            <span class="tag is-warning">
              {{tag.name}}
            </span>
          </a>
          {% endfor %}
        </p>
      </div>

      <!-- buy me a coffee -->
      <div class="level-right">
        <link href="https://fonts.googleapis.com/css?family=Cookie" rel="stylesheet">
        <a class="bmc-button has-text-centered"
          target="_blank" href="https://www.buymeacoffee.com/8owKkSBUC"><img src="https://www.buymeacoffee.com/assets/img/BMC-btn-logo.svg"
            alt="Buy me a coffee"><span style="margin-left:5px">Buy
            me a coffee</span></a>
      </div>
    </div>
  </div>
  <br><br>

  <div id="disqus_thread">
    <div id="comments"></div>
    <script>
      (function () { // DON'T EDIT BELOW THIS LINE
        var d = document,
          s = d.createElement('script');
        s.src = 'https://python-cheatsheet.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
      })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a>
    </noscript>
  </div>

  <!-- delete modal -->
  <div id="deleteModal" class="modal">
    <div id="articleModalBackground" class="modal-background"></div>
    <div class="modal-content box has-text-centered section">
      <h3 class="subtitle">Do you want to Delete {{ post.title }}?</h3>
      <br>
      <div class="columns is-centered">
        <div class="column is-3">
          <form action="{{ url_for('dashboard.delete_post', url=post.url) }}" method=post>
            <input type="hidden" name="entry_id">
            <button class="button is-danger is-outlined">Delete</button>
          </form>
        </div>
        <div class="column is-3">
          <button id="cancel" class="button is-outlined">Cancel</button>
        </div>
      </div>
    </div>
    <button id="closeBtn" class="modal-close is-large" aria-label="close"></button>
  </div>
{% endblock main_column %}

<!-- sidebar -->
{% block side_column %}
  {% include 'main/_default_sidebar.html' %}
  <!-- load the article in the sidebar only in mobil view -->
  {% include 'main/_mobile_article.html' %}
{% endblock side_column %}


{% block js %}
  <!-- addthis javascript -->
  <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5b05cb2ae9e75f31"></script>

  <!-- addthis customize -->
  <script type="text/javascript">
    var addthis_share = {
      url: "www.pythoncheatsheet.org/blog/{{ post.url }}",
      title: "{{ title }} - {{ g.site_name }}",
    };
  </script>
{% endblock js %}

app/templates/main/author.html
{% extends "base_sidebar.html" %}


{% block seo %}
  <link rel="canonical" href="https://www.pythoncheatsheet.org/author/{{ user.username }}">
  <meta property="og:url" content="https://www.pythoncheatsheet.org/author/{{ user.username }}">
  <meta name="description" content="{{ user.username }} - {{ g.md(about_me) }}">
  <meta property="og:description" content="{{ user.username }} - {{ g.md(about_me) }}">
  <meta name="twitter:description" content="{{ user.username }} - {{ g.md(about_me) }}" />
{% endblock seo %}

{% block stylesheet %}
  <link rel="stylesheet" href="{{ url_for( "static", filename="css/carbon-blog.min.css" ) }}">
{% endblock stylesheet %}


{% block main_column %}
<!-- avatar -->
<section class="is-centered">

  <!-- avatar -->
  <nav class="level">
    <p class="level-item has-text-centered">
      <img style="border-radius:50%" src="{{ user.avatar(180) }}" alt="" style="height: 180px;">
    </p>
  </nav>

  <!-- social media -->
  <div class="container column is-3">
    <nav class="level is-mobile">
      <!-- website -->
      {% if user.website %}
        <a href="{{ user.website }}" class="level-item">
          <span class="icon is-medium ">
            <i class="fas fa-link fa-lg "></i>
          </span>
        </a>
      {% endif %}

      <!-- github -->
      {% if user.github %}
        <a href="{{ user.github }}" class="level-item ">
          <span class="icon is-medium ">
            <i class="fab fa-github fa-lg"></i>
          </span>
        </a>
      {% endif %}

      <!-- twitter -->
      {% if user.twitter %}
        <a href="{{ user.twitter }}" class="level-item">
          <span class="icon is-medium ">
            <i class="fab fa-twitter fa-lg"></i>
          </span>
        </a>
      {% endif %}
    </nav>
  </div>

  <!-- username or screen name -->
  <div>
    {% if user.screen_name %}
      <h1 class="subtitle is-3 level-item is-size-4-mobile">About {{ user.screen_name }}</h1>
    {% else %}
      <h1 class="title level-item">About {{ user.username }}</h1>
    {% endif %}
  </div>

  <!-- resumé -->
  <section class="content">
    {% if user.about_me %}
      <p>{{ g.md(about_me)|safe }}</p>
    {% endif %}
    <!--  -->
    {% if user == current_user %}
      <div class="has-text-right">
        <a class="tag is-warning" href="{{ url_for('dashboard.edit_profile', username=current_user.username) }}" aria-current="page">Edit Profile</a>
      </div>
    {% endif %}
  </section>
  <br>

  <!-- blog posts -->
  <div>
    <h2 class="subtitle is-3 level-item is-size-4-mobile">Blog Posts by {{ user.username }}</h2>
    <ul style="list-style-type:disc">
      {% for post in my_posts %}
        <li>
          <a href="{{ url_for('main.article', url=post.url) }}">{{ post.title }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>

</section>
{% endblock main_column %}

{% block side_column %}
  {% include 'main/_default_sidebar.html' %}
{% endblock side_column %}

app/templates/main/blog.html
{% extends "base_sidebar.html" %}

{% block seo %}
  <link rel="canonical" href="https://www.pythoncheatsheet.org/blog">
  <meta property="og:url" content="https://www.pythoncheatsheet.org/blog">
  <meta name="description" content="Python cheat sheet and Articles for Beginner and Advanced Python Developers. This blog tries to provide a basic reference for beginner and advanced developers, lower the entry barrier for newcomers and help veterans refresh the old Python tricks.">
  <meta property="og:description" content="Python cheat sheet and Articles for Beginner and Advanced Python Developers. This blog tries to provide a basic reference for beginner and advanced developers, lower the entry barrier for newcomers and help veterans refresh the old Python tricks.">
  <meta name="twitter:description" content="Python cheat sheet and Articles for Beginner and Advanced Developers." />
{% endblock seo %}

{% block stylesheet %}
  <link rel="stylesheet" href="{{ url_for( "static", filename="css/carbon-blog.min.css" ) }}">
{% endblock stylesheet %}



  {% block main_column %}
    <h1 class="is-hidden-tablet is-hidden-mobile">Blog Python Cheat sheet</h1>
    <br>
    {% for post in all_posts.items %}
      {% include 'main/_post.html' %}
    {% endfor %}

      {% include 'main/_pagination.html' %}

  {% endblock main_column %}


{% block side_column %}
  {% include 'main/_default_sidebar.html' %}

  <!-- load the posts in the sidebar only in mobil view -->
  <div class="is-hidden-tablet">
    {% for post in all_posts.items %}
      {% include 'main/_post.html' %}
    {% endfor %}
  </div>
{% endblock side_column %}

{% block empty_blog %}
  {% if blog_posts|length == 0 %}
  <section class="section">
    <h1 class="title is-1 has-text-centered blog-no-posts">Nothing Yet 🙄</h1>
  </section>
  {% endif %}
{% endblock empty_blog %}

app/templates/main/search.html
{% extends "base.html" %}
<!--  -->
{% block content %}
<!--  -->

<section class="container column is-8 section">
    <!-- title -->
    <h1 class="subtitle is-2 underline-results">Search results for
        <i>"{{ g.search_form.q.data }}"</i>
    </h1>

    <!-- display if no results -->
    {% if total == 0 %}
    <div class="search-no-results">
        <hr>
        <p class="subtitle is-5 is-pulled-right">
            <i>{{ total }} results</i> 🙄
            <a onclick="goBack()" href="javascript:void(0);">Go Back</a>.
        </p>
    </div>
    {% endif %}

    <!-- the results -->
    <ul>
        {% for post in posts %}
        <li class="search-body ">

            <!-- post title -->
            <a class="subtitle is-4 search-link " href="{{ url_for( 'main.article', id=post.id) }} ">{{ post.title }}</a>

            <!-- body -->
            <p>{{ g.md(post.body) | truncate(300, False) | safe }}</p>
        </li>
        <hr>{% endfor %}
    </ul>
    {% if total > 0 %}
    <p class="is-pulled-right subtitle is-5 goBack-search">
        <i>{{ total }} results.</i>
        <a onclick="goBack()" href="javascript:void(0);">Go Back</a>.
    </p>
    <br>

    <br> {% endif %}

</section>

{% block js %}
    <script>s
        function goBack() {
            window.history.go(-2);
        }
    </script>
{% endblock js %}

{% endblock content %}

app/templates/main/tags.html
{% extends "base_sidebar.html" %}

{% block seo %}
  <link rel="canonical" href="https://www.pythoncheatsheet.org/tags">
  <meta property="og:url" content="https://www.pythoncheatsheet.org/tags">
  <meta name="description" content="Blog Tags. Python cheat sheet and Articles for Beginner and Advanced Developers. This blog tries to provide a basic reference for beginner and advanced developers, lower the entry barrier for newcomers and help veterans refresh the old tricks.">
  <meta property="og:description" content="Blog Tags. Python cheat sheet and Articles for Beginner and Advanced Developers. This blog tries to provide a basic reference for beginner and advanced developers, lower the entry barrier for newcomers and help veterans refresh the old tricks.">
  <meta name="twitter:description" content="Blog Tags. Python cheat sheet and Articles for Beginner and Advanced Developers. This blog tries to provide a basic reference for beginner and advanced developers, lower the entry barrier for newcomers and help veterans refresh the old tricks." />
{% endblock seo %}

{% block stylesheet %}
  <link rel="stylesheet" href="{{ url_for( "static", filename="css/carbon-blog.min.css" ) }}">
{% endblock stylesheet %}

{% block main_column %}
  <div class="">
    {% if all_tags %}<br>
      <h1 class="subtitle is-3">
        <span class="icon">
          <i class="fas fa-tags"></i>
        </span>
        <span aria-hidden="true"></span>
        _Tags:</h1>
      <br> {% for tag in all_tags%}
      <a href="{{ url_for('main.tag', tag=tag.name) }}">
        <span class="tag is-warning is-large tag-page">{{ tag.name }}</span>
      </a>
      {% endfor %}
      <br>
      <br>
    {% else %}
      <section class="section">
        <h1 class="title is-1 has-text-centered blog-no-posts">Nothing Yet 🙄</h1>
      </section>
    {% endif %}
  </div>
{% endblock main_column %}

{% block side_column %}
  {% include 'main/_default_sidebar.html' %}

  <div class="is-hidden-tablet">
    {% if all_tags %}<br>
      <h1 class="subtitle is-3">
        <span class="icon">
          <i class="fas fa-tags"></i>
        </span>
        <span aria-hidden="true"></span>
        _Tags:</h1><br>
      {% for tag in all_tags%}
      <a href="{{ url_for('main.tag', tag=tag.name) }}">
        <span class="tag is-warning is-large tag-page">{{ tag.name }}</span>
      </a>
      {% endfor %}
      <br>
      <br>
    {% else %}
      <section class="section">
        <h1 class="title is-1 has-text-centered blog-no-posts">Nothing Yet 🙄</h1>
      </section>
    {% endif %}
  </div>
{% endblock side_column %}